<?
	require "conexao.php";
?>	
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<? include "seo.php"; ?>
<? include "base.php"; ?>
<? include "analytics.php"; ?>
<link href="css/lemarc.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="plugins/banner/engine1/style.css" />
<script type="text/javascript" src="plugins/banner/engine1/jquery.js"></script>
</head>

<body>
<!-- conteudo Home -->
<div id="home">
	<? include "topo.php"; ?>
	<div style="margin:0 auto; width:1000px;">
    <!-- Banner -->
    	<!-- Start WOWSlider.com BODY section -->
<div id="wowslider-container1">
<div class="ws_images">
	<ul>
<?
		$i1 = 0;
		$sql_banners1 = mysql_query("SELECT * FROM banners ORDER BY id DESC LIMIT 0,15");
		while($dados_banners1 = mysql_fetch_array($sql_banners1)){
?>		
		<li>
        	<a href="<?=$dados_banners1[link]?>">
            <img src="fotos/banners/<?=$dados_banners1[banner]?>" width="830" height="360" alt="<?=$dados_banners1[legenda]?>" title="<?=$dados_banners1[legenda]?>" id="wows1_0"/>
            </a>
            </li>
<?
		$i1++;
		}
?>		
	</ul>
</div>
<div class="ws_thumbs">
<div>
<?
	$i = 1;
	$sql_banners = mysql_query("SELECT * FROM banners ORDER BY id DESC LIMIT 0,15");
	while($dados_banners = mysql_fetch_array($sql_banners)){
?>
<a href="#" title="<?=$dados_banners[legenda]?>"><img src="fotos/banners/<?=$dados_banners[banner]?>" width="110" height="60" alt="" /></a>
<?
	$i++;
	}
?>	
</div>
</div>
<!-- Generated by WOWSlider.com v4.3 -->
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="plugins/banner/engine1/wowslider.js"></script>
	<script type="text/javascript" src="plugins/banner/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
    <!-- Banner -->
    
    
    
	</div>
</div>
<!-- conteudo Home -->    
    <!-- Div Produtos -->
    <div style="width:100%; height:519px;background:url(img/bg_home.jpg) repeat-x;">
        <div id="div_produtos_home">
            <span class="albertus39cinza" style="font-weight:bold;">Produtos</span>
            <div class="clear"></div>
<?
	$sql_produtos = mysql_query("SELECT * FROM produtos ORDER BY RAND() LIMIT 0,4");
	while($dados_produtos = mysql_fetch_array($sql_produtos)){
	$capa = lista("SELECT * FROM fotos_produtos WHERE capa='s' AND produtos_id='".$dados_produtos[id]."'");
		if($capa[foto]!=''){
			$imagem = $capa[foto];
		}else{
			$imagem = "modelo.png";
		}
?>            
            <div class="box_produtos_home">
                <h1><?=$dados_produtos[nome]?></h1>
                <img src="plugins/imagens/imagem.php?arquivo=<?=$imagem?>&largura=160&altura=200" width="160" height="200" border="0" />
                <a href="produto/<?=$dados_produtos[id]?>-<?=$dados_produtos[linkchave]?>" class="botao_home" style="text-decoration:none;">VER DETALHES [+]</a>
            </div>
<?
	}
?>            


            <div class="clear"></div>       
        </div>
        
	</div>
    <!-- Div Produtos -->

<? include "rodape.php"; ?>

</body>
</html>